### ISSUE TITLE
capture all OCW feedback

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/asb-hack#238]
- challenges
- features
- chats
- demos
- videos (should all be posted to our RDC-Demos channel - ping @AAkindele  if you need help)

Checklist
- Demo and Overview videos uploaded to RDC Stream channels
  - [x] ASB Overview 1: https://msit.microsoftstream.com/video/e59c0840-98dc-a7ab-5f7b-f1ebb810bf2b
  - [x] ASB Overview 2: https://msit.microsoftstream.com/video/e59c0840-98dc-a7ab-1e9d-f1ebb810d1a2
  - [x] PnP ASB Spike demo: https://msit.microsoftstream.com/video/9c970840-98dc-869c-efd0-f1ebbe3b303f
  - [ ] PnP ASB Upskilling demo: https://msit.microsoftstream.com/video/ea970840-98dc-869c-c91a-f1ebba76ea59
- [x] (NOTE: added to triage) Cleanup and merge "Isolated Traffic Control" branch https://github.com/retaildevcrews/ocw-asb-spikes/commits/spikes/baseA
- [x] (NOTE: added to triage) Cleanup and merge "Cloud Native Monitoring" branch https://github.com/retaildevcrews/ocw-asb-spikes/tree/spikes/workA

**Comment by joheec** [comment]
- Include architecture diagram in README.md (https://github.com/mspnp/aks-secure-baseline)
- Include network flow (https://github.com/retaildevcrews/ngsa/tree/jkeane/archdocs/docs/arch#pnp-request-routing---monitoring-dev-cluster) somewhere in the repo
- ASB Overview 1 (sharepoint): https://microsoft-my.sharepoint.com/:v:/p/jofultz/ERhDML2oYO1MgETIM8cIQOUBwrvc-4kZQahaaiFSUew3Ug
- ASB Overview 1 (stream): https://msit.microsoftstream.com/video/e59c0840-98dc-a7ab-5f7b-f1ebb810bf2b?channelId=533aa1ff-0400-85a8-6076-f1eb81fb8468
- ASB Overview 2 (sharepoint): https://microsoft-my.sharepoint.com/:v:/p/jofultz/Eb-xg-Hube9CqGZGFzQxLOsBYScbLdfrE2IaKyp28Q7mpQ
- ASB Overview 2 (stream): https://msit.microsoftstream.com/video/e59c0840-98dc-a7ab-1e9d-f1ebb810d1a2?channelId=533aa1ff-0400-85a8-6076-f1eb81fb8468
- ASB Overview 3 (sharepoint): https://microsoft-my.sharepoint.com/:v:/p/jofultz/ESGmKtK8YLxFscZQFqaA_PcBXiUNKTjN3DyrNTlQEFc64A
- Did not use "Challenges" folder
- Love the social event, virtual shopping
- Upskilling demos: https://web.microsoftstream.com/video/ea970840-98dc-869c-c91a-f1ebba76ea59
- Challenges were key
- Hosting script should include promoting using triage. Enjoyed
- End to end docs for Traefik configs and features
- Issues with copy/paste
- Cadence for breaks
- Bash Notebook
- Notes on ways to speed up testing

**Comment by bartr** [comment]
Are those videos in our channel?  If not, let's move them there and drop the sharepoint reference..

Need to explicitly call out Calf Pulling 101 :)

**Comment by gortegaMS** [comment]
**Add to triage**

- [ ] Create a triage item with the entire OCW feedback items list

_Individual triage items from feedback_

- [ ] It would have been better to highlight how the group approached the project statement instead of just showing notable features we added. 
- [ ] Demos showed what we delivered; however, there was also a good amount of effort researching and understanding other aspects of the project that do not have a visual representation.
- [ ] Several folks did not have as much experience with ASB, not sure if I saw a video walkthrough on ASB on the RDC demos channel but this would have been great for quick upskilling
- [ ] We need to figure out how to add a “Join” button to our chats.
