### ISSUE TITLE
CSE feedback - add copy fence button in VS Code / Codespaces

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/asb-hack#264]

**Comment by bartr** [comment]
- add to CSE feedback
- open an issue / discussion in the GitHub forum

**Comment by kev-ms** [comment]
Title: 
VSCode and Github Codespaces are missing button to copy code fences to the clipboard in markdown preview.

Steps to Reproduce:
1. Open a markdown file with bash/code snippet in VSCode or Github Codespaces. 
2. Open the markdown preview window (F1, Markdown: Open Preview)
3. Click on any command/code in markdown and observe that there is no copy button.

Expected Behavior:
Markdown Preview in both VSCode and Github Codespaces should have copy fence button like Github repo.
​​​​​​​​​​​​​​​
![image](https://user-images.githubusercontent.com/71272427/121087455-1a078400-c7aa-11eb-8a97-58bf8d7ab5b1.png)

**Comment by kev-ms** [comment]
GH Issue: https://github.com/microsoft/vscode/issues/125756
CSE Feedback: 455125
