### ISSUE TITLE
Investigate Azure lab services

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/asb-hack#360]
Is this service something we can leverage for hosting hacks?
https://azure.microsoft.com/en-us/services/lab-services

**Comment by bartr** [comment]
@AAkindele gets a "see something, say something" trophy!!!

If you're interested, I'm going to setup a conversation with the team. Will need to be small audience. It could result in a home for akdc-kind!

**Comment by bartr** [comment]
I was able to get this working very easily via the portal. 
- use Ubuntu 20.04 LTS (NOT the HPC variant!)
- add an artifact that runs this bash scrip
  - https://raw.githubusercontent.com/bartr/dev-labs/main/akdc.sh
  - akdc.sh
  - your user ID
- I'm going to update the akdc repo to use labs instead of raw VMs as it's much easier and you get additional capabilities like auto-start and auto-shutdown

Still planning to talk to the labs team in DevDiv to see how we would "publish" "recipes"

We can close this after that meeting and track with new issues

**Comment by bartr** [comment]
- Codespaces has an "always on" feature coming so I don't think there's a need for this going forward
- If we find a customer need, we'll re-address
- closing
